=== YxWMDS/xml_pz/src/Planes.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="planes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="plane" type="plane" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="plane">
        <xs:sequence>
            <xs:element name="type" type="xs:string" />
            <xs:element name="seats" type="seatsType" />
            <xs:element name="ammunition" type="xs:boolean" />
            <xs:element name="rockets" type="rocketsType" />
            <xs:element name="radar" type="xs:boolean" />
            <xs:element name="parameters">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="length" type="xs:positiveInteger" />
                        <xs:element name="width" type="xs:positiveInteger" />
                        <xs:element name="height" type="xs:positiveInteger" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" />
    </xs:complexType>

    <xs:simpleType name="seatsType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="2"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="rocketsType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="10"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== YxWMDS/xml_pz/src/Planes.xml
<?xml version="1.0" encoding="UTF-8"?>

<planes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="Planes.xsd">

    <plane id ="1">
        <type>Support</type>
        <seats>1</seats>
        <ammunition>true</ammunition>
        <rockets>8</rockets>
        <radar>true</radar>
        <parameters>
            <length>15</length>
            <width>8</width>
            <height>4</height>
        </parameters>
    </plane>

    <plane id ="2">
        <type>Escort</type>
        <seats>2</seats>
        <ammunition>false</ammunition>
        <rockets>0</rockets>
        <radar>true</radar>
        <parameters>
            <length>12</length>
            <width>6</width>
            <height>3</height>
        </parameters>
    </plane>

    <plane id ="3">
        <type>Fighter</type>
        <seats>1</seats>
        <ammunition>true</ammunition>
        <rockets>10</rockets>
        <radar>true</radar>
        <parameters>
            <length>18</length>
            <width>7</width>
            <height>3</height>
        </parameters>
    </plane>

</planes>
